# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl secrets set --stage "RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}" "MAILTRAP_API_KEY=${{ secrets.MAILTRAP_API_KEY }}" "MAILER_FROM_ADDRESS=${{ secrets.MAILER_FROM_ADDRESS }}"
      - run: flyctl deploy --remote-only
