name: ruby head test

on:
  schedule:
    - cron: '0 1 * * 1-5' # 平日のJST10時
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruby-head-test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/composite/backend-test
        with:
          custom-ruby-version: 'debug'
