name: ruby head test

on:
  schedule:
    - cron: '0 1 * * 1-5' # 平日のJST10時
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruby-head-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/composite/backend-test/action.yml
        with:
          custom-ruby-version: 'debug'
